#ifndef _SESSION_PARAMETERS_CHECK_H_
#define _SESSION_PARAMETERS_CHECK_H_
enum
{
    SESSION_PARAMES_ER_CODE_ILLEGAL_SESSION_ID = 0,
    SESSION_PARAMES_ER_CODE_ILLEGAL_RUNNING_DURATION = 1,
    SESSION_PARAMES_ER_CODE_ILLEGAL_LOG_INTERVAL = 2,
    SESSION_PARAMES_ER_CODE_ILLEGAL_LOG_FEATURES_LENGTH = 3,
    SESSION_PARAMES_ER_CODE_ILLEGAL_LOG_FEATREUS_ID = 4,
    SESSION_PARAMES_ER_CODE_ILLEGAL_PREPARATION_STATUS_LENGTH = 5,
    SESSION_PARAMES_ER_CODE_ILLEGAL_PREPARATION_STATUS_FEATRUES_ID = 6,
    SESSION_PARAMES_ER_CODE_ILLEGAL_PREPARATION_STATUS_FEATRUSE_ID_LENGTH = 7,
    SESSION_PARAMES_ER_CODE_ILLEGAL_PREPARATION_STATUS_FEATRUSE_ID_VALUE = 8,
    SESSION_PARAMES_ER_CODE_ILLEGAL_RUNNING_STATUS_LENGTH = 9,
    SESSION_PARAMES_ER_CODE_ILLEGAL_RUNNING_STATUS_N_SESSION_START_TIME = 10, // session start time not 0
    SESSION_PARAMES_ER_CODE_ILLEGAL_RUNNING_STATUS_N_TIME = 11,               // session status_n time is 0
    SESSION_PARAMES_ER_CODE_ILLEGAL_RUNNING_STATUS_N_SESSION_STOP_TIME = 12,  // session stop time not ffff
    SESSION_PARAMES_ER_CODE_ILLEGAL_RUNNING_STATUS_N_LENGTH = 13,
    SESSION_PARAMES_ER_CODE_ILLEGAL_RUNNING_STATUS_N_FEATUREIS_ID = 14, //
    SESSION_PARAMES_ER_CODE_ILLEGAL_RUNNING_STATUS_N_FEATRUSE_ID_LENGTH = 15,
    SESSION_PARAMES_ER_CODE_ILLEGAL_RUNNING_STATUS_N_FEATRUSE_ID_VALUE = 16,
    SESSION_PARAMES_ER_CODE_RUNNING_STATUS_SESSION_TIME_NOT_SORTING = 17, // session status_n time disorder
    SET_SESSION_PACKET_ERROR = 0xFF,                                      // there is an error in the data packet
};

unsigned char session_parames_check(unsigned char *error_code);

#endif
